export default {
  "en": "gb",
  "zh": "cn",
  "hi": "in",
  "es" : "es",
  "ar" : "sy",
  "fr" : "fr",
  "ms" : "my",
  "ru" : "ru",
  "bn" : "bd",
  "pt" : "pt",
  "de" : "de",
  "ja" : "jp",
  "fa" : "ir",
  "sw" : "ke",
  "jv" : "id",
  "te" : "in",
  "tr" : "tr",
  "ko" : "kp",
  "mr" : "in",
  "ta" : "lk",
  "vi" : "vn",
  "it" : "it",
  "ha" : "ng",
  "th" : "th"
}